### ISSUE TITLE
crs_write raise exception when generating a file when operator is omitted

### ISSUE THREAD

**Issue by mirkodziadzka-avi** [digitalwave/msc_pyparser#12]
As shortly discussed in https://github.com/digitalwave/msc_pyparser/issues/9#issuecomment-581130642, I see an issue when using crs_write

# how to reproduce

use latest master version 7d7fa7feac7e24d792db9cecf689557af7f59359

Use the following input:

```
SecRule ARGS "foo" "id:42,phase:2,block,t:none"
```

crs_read will crate the following file

```.yaml
- actions:
  - act_arg: '42'
    act_name: id
    act_quote: no_quote
    lineno: 1
  - act_arg: '2'
    act_name: phase
    act_quote: no_quote
    lineno: 1
  - act_name: block
    act_quote: no_quote
    lineno: 1
  - act_arg: none
    act_name: t
    act_quote: no_quote
    lineno: 1
  chained: false
  lineno: 1
  operator: ''
  operator_argument: foo
  type: SecRule
  variables:
  - ARGS
```

crs_write will throw an exception on this

```
$ ./crs_write.py testy testz
Parsing CRS structure: testy/test.yaml
Exception catched -  (<class 'KeyError'>, KeyError('oplineno'), <traceback object at 0x108e45280>)
Traceback (most recent call last):
  File "./crs_write.py", line 70, in <module>
    mwriter.generate()
  File "/Users/mirko/.local/share/virtualenvs/mirko-jYbmoHav/lib/python3.7/site-packages/msc_pyparser-0.2.3-py3.7.egg/msc_pyparser.py", line 721, in generate
    self.make_secrule(i)
  File "/Users/mirko/.local/share/virtualenvs/mirko-jYbmoHav/lib/python3.7/site-packages/msc_pyparser-0.2.3-py3.7.egg/msc_pyparser.py", line 699, in make_secrule
    if r['lineno'] < r['oplineno']:
KeyError: 'oplineno'
```

When replacing the rule with

```
SecRule ARGS "@rx foo" "id:42,phase:2,block,t:none"
```

it will work

**Comment by mirkodziadzka-avi** [comment]
cc: @MirkoDziadzka

**Comment by mirkodziadzka-avi** [comment]
My proposal would be to parse this short form as if `@rx` would be there. Then the read/write cycle would modify the rule, but - in my personal opinion - the version with implicit operator should be deprecated.

**Comment by airween** [comment]
Hi @mirkodziadzka-avi,

so many thanks again for your remark. PR #13 fixes this problem, I close the issue.

**Comment by mirkodziadzka-avi** [comment]
Thanks for the fix.

I transformed my rulset `modsec-lang -> YAML -> modsec-lang -> yaml` for verification.

- The output from 2 and 4 is identical
- If I ignore all whitespaces, the output from 1 and 3 is identical, except minor reformatting

As you did predicted:
```
ARGS,ARGS -> ARGS|ARGS
SecRule ARGS foo -> SecRule ARGS "foo"
```

and aditional:
```
SecRule ARGS "foo" "\
 id:42
```
became
```
SecRule ARGS "foo" \
 "id:42
```

At the end, a very impressive performance:

```
$ cat original/*.conf | wc -l
  431619
$ diff -w -r original regenerated | wc -l
      22
```

**Comment by airween** [comment]
Oh, nice to see the performance :).

Anyway, your additional example can be prevented - the `MSCWriter` class follows the [expected CRS formatting](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.3/dev/CONTRIBUTING.md#general-formatting-guidelines-for-rules-contributions) rules, and of course, you can overwrite it as you want.

If you interesting, check the [beautifier](https://github.com/digitalwave/msc_pyparser/blob/master/examples/example7_beautifier.py) [examples](https://github.com/digitalwave/msc_pyparser/blob/master/examples/example7a_beautifier.py) (both has a short text description with same name).
